# -*- coding: utf-8 -*-
"""test_classifier.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Klj-Q55amPlAWjEBHJEkeDUZYGhGOTSU
"""

from tensorflow.keras.models import load_model

import numpy as np

from google.colab import files
uploaded = files.upload()

from google.colab import files
uploaded = files.upload()

model=load_model('snake_pred9.h5')

import tensorflow as tf

image = 'anaconda1.jpg'

import cv2

def prepare(image):
  IMG_SIZE=384
  img_array = cv2.imread('anaconda1.jpg', cv2.IMREAD_COLOR)
  new_array = cv2.resize(img_array, (IMG_SIZE, IMG_SIZE))
  return new_array.reshape(-1, IMG_SIZE, IMG_SIZE, 3)

y=model.predict([prepare('anaconda1.jpg')])

print(y)
#the class labels 0 and 1 should be spelt out for anaconda and python.
score = y[0]
print(
    "This is %.2f percent chance anaconda and %.2f python."
    %(100*(1-score), 100*score)
)
from matplotlib import pyplot as plt

img = cv2.imread('anaconda1.jpg',0)
plt.imshow(img, interpolation = 'bicubic')
plt.xticks([]), plt.yticks([])  
plt.show()
#the picture of the anaconda
